source 'https://api.berkshelf.com'

cookbook 'apt', '>= 2.3.8', git: 'https://github.com/opscode-cookbooks/apt', tag: 'v2.3.8'
cookbook 'ark', git: 'https://github.com/opscode-cookbooks/ark', tag: 'v0.9.0'
cookbook 'bluepill', '>= 2.3.1', git: 'https://github.com/opscode-cookbooks/bluepill', tag: 'v2.3.1'
cookbook 'build-essential', '>= 1.4.2', git: 'https://github.com/opscode-cookbooks/build-essential', tag: 'v2.1.2'
cookbook 'java', '>= 1.19.2', git: 'https://github.com/opscode-cookbooks/java', tag: 'v1.28.0'
cookbook 'monit', '>= 0.6', git: 'https://github.com/apsoto/monit'
cookbook 'ohai', '>= 1.1.12', git: 'https://github.com/opscode-cookbooks/ohai', tag: 'v2.0.1'
cookbook 'python', '>= 1.4.6', git: 'https://github.com/poise/python', tag: 'v1.4.6'
cookbook 'rsyslog', '>= 1.11.0', git: 'https://github.com/opscode-cookbooks/rsyslog', tag: 'v1.11.0'
cookbook 'windows', '>= 1.30.0', git: 'https://github.com/opscode-cookbooks/windows', tag: 'v1.30.2'
cookbook 'yum', git: 'https://github.com/opscode-cookbooks/yum', tag: 'v3.4.0'
cookbook 'yum-epel', '>= 0.3.4', git: 'https://github.com/opscode-cookbooks/yum-epel', tag: 'v0.5.1'
cookbook 'elasticsearch', git: 'https://github.com/elasticsearch/cookbook-elasticsearch', tag: '0.3.11'
cookbook 'mongodb', git: 'https://github.com/edelight/chef-mongodb'
cookbook 'papertrail', git: 'https://github.com/librato/papertrail-cookbook', tag: '0.0.7'
cookbook 'aws-tag', git: 'https://github.com/stuart-warren/chef-aws-tag'
cookbook 'cron', '>= 1.6.1'
